insert null into Integer column using JDBC
eugenp/tutorials pull request #10807
Opened 2021-05-25 22:17 UTC by mladensavic94

2021-06-02 19:56 UTC, JonCook requested changes
Hi @mladensavic94 - a few things to clean up there. Thanks.

2021-06-02 19:56 UTC, JonCook commented on persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/insertnull/DBConfig.java
> +            Class.forName("org.h2.Driver");
Do we need this Class.forName - looks redundant?

2021-06-02 19:56 UTC, JonCook commented on persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/insertnull/DBConfig.java
> +    public static Connection getConnection() throws Exception {
Can we throw the proper Exception type here? SQLException

2021-06-02 19:56 UTC, JonCook commented on persistence-modules/core-java-persistence-2/src/main/java/com/baeldung/insertnull/DBConfig.java
> +    private static void createPersonTable() {
Let's use try-with resources in this method and get rid of the printStacktrace

2021-06-02 19:56 UTC, JonCook commented on persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/insertnull/InsertNullUnitTest.java
> +import org.hamcrest.MatcherAssert;
Let's please remove the unused import statements.

2021-06-02 19:56 UTC, JonCook commented on persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/insertnull/InsertNullUnitTest.java
> +        } catch (Exception ignored) {
Why do we need these catch Exception statements if they don't do anything and the method already throws Exception. let's remove them from all the tests.

2021-06-08 02:53 UTC, eric-martin commented on persistence-modules/core-java-persistence-2/src/test/java/com/baeldung/insertnull/InsertNullUnitTest.java
> +            if (person.getAge() == null)
Add braces for one line if/else statements

2021-06-09 09:15 UTC, merged