BAEL-4932-Email Validation in Java
eugenp/tutorials pull request #11084
Opened 2021-07-29 10:52 UTC by gupta-ashu01

BAEL-4932-Email Validation in Java

2021-08-02 13:31 UTC, JonCook requested changes

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/README.md
> +- [Email Validation in Java](https://drafts.baeldung.com/wp-admin/post.php?post=101820&action=edit)
Hi @gupta-ashu01 - let's please revert the README file. The editorial team will take care of that once the article is published.

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/pom.xml
> +
Can we clean up these empty lines?

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/src/main/java/com/baeldung/emailvalidation/EmailValidation.java
> +        EmailValidator validator = EmailValidator.getInstance();
Can't we just do this in one line?
`return EmailValidator.getInstance().isValid(emailAddress)`

I don't think we even need a helper method in this case. Let's remove it.

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/src/main/java/com/baeldung/emailvalidation/EmailValidation.java
> +        String regExPattern = "^(.+)@(\\S+)$";
Can we remove all these empty lines in the methods. Maybe one after the regex string is OK.

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/src/main/java/com/baeldung/emailvalidation/EmailValidation.java
> +        Pattern pattern = Pattern.compile(regExPattern);
Can't we put the pattern code in a common private method to avoid duplicating it so many times?

2021-08-02 13:31 UTC, JonCook commented on core-java-modules/core-java-string-algorithms-3/src/test/java/com/baeldung/emailvalidation/EmailValidationUnitTest.java
> +        boolean result = EmailValidation.usingStrictRegEx(emailaddress);
Likewise, no need for all these blank lines and can't we just make a call to the EmailValidation in the assert method directly to make the code more concise?

2021-08-07 06:34 UTC, gupta-ashu01 commented
Hi @JonCook ,
Will open a new pull request with the updated version.

2021-08-07 06:34 UTC, closed without merging