Update optaplanner example
eugenp/tutorials pull request #12467
Opened 2022-07-08 14:38 UTC by dupliaka

Moved to 8.24.0.Final version
Removed deprecated drools calculation
Added constraints stream solver
Updated to solver config java api

2022-07-08 18:00 UTC, yurloc reviewed
A few minor improvements suggested. Otherwise looks good to me.

Of course, this shouldn't be merged without also updating the [blog post](https://www.baeldung.com/opta-planner) accordingly.

2022-07-08 18:00 UTC, yurloc commented on optaplanner/src/main/java/com/baeldung/optaplanner/CourseSchedule.java
> +
```suggestion
```
Please avoid consecutive blank lines.

2022-07-08 18:00 UTC, yurloc commented on optaplanner/src/main/java/com/baeldung/optaplanner/Lecture.java
> +    }
```suggestion
    }

```

2022-07-08 18:00 UTC, yurloc commented on optaplanner/src/test/java/com/baeldung/optaplanner/test/CourseScheduleConstraintProviderUnitTest.java
> +    public void testCourseScheduleConstraint(){
```suggestion
    public void testCourseScheduleConstraint() {
```

2022-07-08 18:00 UTC, yurloc commented on optaplanner/src/test/java/com/baeldung/optaplanner/test/OptaPlannerUnitTest.java
> +
```suggestion
```
Removing an extra blank line.

2022-07-08 18:00 UTC, yurloc commented on optaplanner/src/test/java/com/baeldung/optaplanner/test/OptaPlannerUnitTest.java
> +        for(long i = 0; i < 10; i++){
```suggestion
        for(long i = 0; i < 10; i++) {
```

2022-07-08 18:13 UTC, yurloc requested changes
@dupliaka The CI fails because the `optaplanner` tutorial can no longer be built using Java 8 (because OptaPlanner 8.24 is being built with Java 11).

To fix that, go to the root `pom.xml` and move two `<module>optaplanner</module>` elements from `default-first` and `integration-lite-first` profiles to `default-jdk9-and-above` and `integration-jdk9-and-above` profiles.

See https://github.com/eugenp/tutorials#profile-based-segregation for explanation of the profiles.

2022-08-18 04:32 UTC, merged

2022-08-18 04:32 UTC, dkapil commented
Thank you for your contribution @dupliaka and @yurloc. PR is merged and article is now updated.

2022-08-19 05:47 UTC, dupliaka commented
Thank you very much! I have notice that there is no mention on ConstraintStream that is provided in test_whenConstraintStreamSolver. It is a major difference since the previous version and it would be much more consistent to mention it in the blog as well. 
You can mention in Scoring section telling simply that there is a better way to define constraints in the lambda function way that allows to cash results and calculate score faster. To do so you just need to define one class (see [CourseScheduleConstraintProvider.java](https://github.com/dupliaka/tutorials/blob/3492fb12de465c280cc2595b7c9a1d08348958d5/optaplanner/src/main/java/com/baeldung/optaplanner/CourseScheduleConstraintProvider.java))

2022-08-19 07:06 UTC, dkapil commented
Thanks @dupliaka . We have opened an internal jira to look into this further.

2022-08-19 07:16 UTC, dupliaka commented
> Thanks @dupliaka . We have opened an internal jira to look into this further.

Great! Thanks for collaboration feel free to reach me out if you would need some additional assistance.