JAVA-14446: Which sub-modules aren't being built
eugenp/tutorials pull request #12662
Opened 2022-08-28 16:57 UTC by freelansam

2022-08-29 04:45 UTC, freelansam commented
retest this please

2022-08-31 15:58 UTC, dkapil requested changes

2022-08-31 15:58 UTC, dkapil commented on pom.xml
> +				<module>kubernetes</module>
let's fix the formatting here.

2022-08-31 15:58 UTC, dkapil commented on spring-cloud-modules/pom.xml
> +        <!--<module>spring-cloud-openfeign-2</module>--> <!-- failing -->
no need to comment this, this should be fixed now. Please update the PR from master

2022-09-01 07:31 UTC, closed without merging