Bael 5649
eugenp/tutorials pull request #12677
Opened 2022-08-31 17:44 UTC by viktorardelean

Article code

2022-09-14 03:03 UTC, bipster requested changes
@viktorardelean In addition to the inline notes, can you:
* Run the code through the Baeldung formatter?
* See why your tests are failing the automated suite? My guess is that your tests require the Spring context, which requires the *IntegrationSuite suffix
* For the package name, instead of `handlermethodargumentresolver` maybe something more friendly like `jsonargs`

2022-09-14 06:53 UTC, viktorardelean commented on spring-web-modules/spring-mvc-basics-5/src/main/java/com/baeldung/handlermethodargumentresolver/UserController.java
> +        // userService.process(firstName, city)
done

2022-09-14 06:53 UTC, viktorardelean commented on spring-web-modules/spring-mvc-basics-5/src/test/java/com/baeldung/handlermethodargumentresolver/UserControllerTest.java
> +class UserControllerTest {
done

2022-09-17 17:29 UTC, bipster approved these changes
Thank you!

2022-09-17 17:30 UTC, merged