Spring Boot with Apache Pulsar
eugenp/tutorials pull request #14341
Opened 2023-07-01 14:27 UTC by neha298

2023-07-05 07:41 UTC, ashleyfrieze requested changes

2023-07-05 07:41 UTC, ashleyfrieze commented on spring-pulsar/README.md
> +- Intro to Apache Pulsar with Spring
We don't need this file yet, please remove.

2023-07-05 07:41 UTC, ashleyfrieze commented on spring-pulsar/pom.xml
> +	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
This file appears to be formatted with `tab` not `space`

2023-07-25 03:32 UTC, KevinGilmore commented on spring-pulsar/src/main/java/com/baeldung/springpulsar/SpringPulsarApplication.java
> +	}
Use spaces instead of tabs to indent

2023-07-25 03:36 UTC, KevinGilmore commented on spring-pulsar/src/test/java/com/baeldung/springpulsar/SpringPulsarApplicationTests.java
> +class SpringPulsarApplicationTests {
Let's follow the class naming convention of *UnitTest

2023-08-02 19:21 UTC, merged