Bael 7131 input stream vs input stream reader in java
eugenp/tutorials pull request #15211
Opened 2023-11-13 12:31 UTC by adalagandev

2023-11-13 16:33 UTC, theangrydev requested changes
I left comments on what changes to make for the PR in Jira

2023-11-27 02:54 UTC, adalagandev commented
> I left comments on what changes to make for the PR in Jira

Thanks. I made the changes based on your comments.

2023-11-27 22:41 UTC, theangrydev requested changes

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +    private Path sharedTempDir = null;
I don't understand the purpose of this field, it is not shared between test method executions, so I'm not sure what "shared" means exactly. Let's keep everything inside the test method and keep the naming clear.

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +    public void givenAString_whenWrittenToFileInputStream_thenShouldMatchWhenRead(@TempDir(cleanup = ALWAYS) Path tempDir) throws IOException {
ALWAYS is already the default behaviour, remove this

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +        try(  FileOutputStream fileOutStream = new FileOutputStream( fileText)){
Fix the formatting - please apply the Baeldung code formatter, which you can find in the style guidelines for your IDE

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +        }
Do not catch exceptions in test code unless you are specifically testing an exception. Remove this and declare throws IOException or throws Exception on all the parent methods.

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstreamreader/InputStreamReaderTest.java
> +    public void givenAString_whenReadByInputStreamReader_thenShouldMatchWhenRead(@TempDir(cleanup = ALWAYS) Path tempDir) throws IOException {
```suggestion
    public void givenAStringWrittenToAFile_whenReadByInputStreamReader_thenShouldMatchWhenRead(@TempDir(cleanup = ALWAYS) Path tempDir) throws IOException {
```

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +            strRet = sb.toString();
Just return the result directly, no need for the variable
```suggestion
            return sb.toString();
```

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +            try(ObjectInputStream input = new ObjectInputStream(fileStream);){
These can be combined into a single try-with-resources, separated with semicolons per resource

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +            try(    ObjectOutputStream objectOutStream  = new ObjectOutputStream(fileOutStream)){
These can be combined into a single try-with-resources, separated with semicolons per resource

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +        String sample = "In this example, we use btye array input stream";
```suggestion
        String sample = "In this example, we use byte array input stream";
```

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +        File fileText = sampleOut.toFile();
```suggestion
        File sampleOutFile = sampleOut.toFile();
```

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +                    break;
Move the condition into the while()

2023-11-27 22:41 UTC, theangrydev commented on core-java-modules/core-java-io-apis-2/src/test/java/com/baeldung/inputstream/InputStreamTest.java
> +            final StringBuilder sb = new StringBuilder();
Drop the final keyword

2024-01-13 16:16 UTC, closed without merging