Move code for Ebook modules
eugenp/tutorials pull request #15297
Opened 2023-11-25 18:48 UTC by ehsansasanian

2023-12-06 14:30 UTC, dkapil requested changes

2023-12-10 22:35 UTC, alvin577austria commented on persistence-modules/spring-data-jpa-simple/README.md
> +This module contains sample e-book code. Therefore, it should not be used to add code for any new article.
Thanks @dkapil 
Hi @ehsansasanian, please update the README with a similar format. Thanks!

2023-12-12 00:23 UTC, ehsansasanian commented on persistence-modules/spring-data-jpa-simple/README.md
> +This module contains sample e-book code. Therefore, it should not be used to add code for any new article.
@alvin577austria Please check https://github.com/eugenp/tutorials/pull/15297/commits/5e22e56a1e5d78926c7eb05633ef86d35d09f7fa and let me know if you need anything else.

2023-12-15 23:57 UTC, alvin577austria commented on persistence-modules/spring-data-jpa-simple/README.md
> +This module contains sample e-book code. Therefore, it should not be used to add code for any new article.
The readme file looks ok to me.

2023-12-16 00:01 UTC, alvin577austria commented
Hi @ehsansasanian 
I have made the initial changes to upgrade the spring-boot-2 submodule to support SpringBoot3
Can you please verify on your end if the build succeeds as well.
Next step is to combine the two submodules into one that is spring-data-jpa-simple module.
Please proceed with this step and let me know if anything is unclear.
Thanks!

2024-01-13 16:16 UTC, closed without merging