adding the parent method. wrapping up structure of tree
eugenp/tutorials pull request #15736
Opened 2024-01-25 22:18 UTC by pedrolopes9-7

2024-02-08 21:54 UTC, JavierPeris requested changes
Please apply Baeldung formatter.

2024-02-20 00:57 UTC, pedrolopes9-7 commented on algorithms-modules/algorithms-miscellaneous-7/src/main/java/com/baeldung/algorithms/parentnodebinaytree/TreeNode.java
> +}
That makes sense, thanks. Will apply

2024-02-20 00:58 UTC, pedrolopes9-7 commented on algorithms-modules/algorithms-miscellaneous-7/src/main/java/com/baeldung/algorithms/parentnodebinaytree/TreeNode.java
> +    }
Sure, I´ve used variables for more meaningful names about what´s happening. But, I think we can explain the if statement in the text

2024-02-20 01:12 UTC, pedrolopes9-7 commented
Hey @JavierPeris, I've made your suggested changes here. Let me know if you agree with the code now, so I can update the article draft.
Thanks!

2024-03-06 17:06 UTC, merged