WIP: Integrate Introduction To Spring Data JPA
eugenp/tutorials pull request #15733
Opened 2024-01-25 20:24 UTC by harry9656

2024-02-04 01:02 UTC, alvin577austria requested changes
Some comments.

2024-02-04 01:02 UTC, alvin577austria commented on persistence-modules/spring-data-jpa-simple/src/main/java/com/baeldung/jpa/schemageneration/HibernateUtil.java
> +import java.util.Objects;
I noticed there are a lot of unused imports across files, I think that is fine as long as the unused imports are not shown in the articles themselves. Can you please check? Thanks!

2024-02-07 06:04 UTC, harry9656 commented on persistence-modules/spring-data-jpa-simple/src/main/java/com/baeldung/jpa/schemageneration/HibernateUtil.java
> +import java.util.Objects;
I Removed unused imports from all the classes.
I double-checked the articles, but we don't show imports inside the articles anyway :)

2024-03-14 21:31 UTC, merged

2024-09-03 19:55 UTC, alvin577austria reviewed
Please move spring-boot-simple inside spring-boot-modules