Stream file
eugenp/tutorials pull request #15804
Opened 2024-02-03 08:46 UTC by Neetika23

2024-02-03 12:08 UTC, vinipx requested changes

2024-02-03 12:08 UTC, vinipx commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    @Test
maybe let's break the line here

2024-02-03 12:08 UTC, vinipx commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    public void whenRangeStreamUsingLimitSkip_thenRangePrints() {
_thenPrintsRange()   maybe?

2024-02-03 12:08 UTC, vinipx commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    public void whenRangeStreamUsingCollectingAndThen_thenRangePrints() {
_thenPrintsRange()   maybe?

2024-02-04 08:43 UTC, Neetika23 commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    @Test
done

2024-02-04 08:44 UTC, Neetika23 commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    public void whenRangeStreamUsingLimitSkip_thenRangePrints() {
done

2024-02-04 08:44 UTC, Neetika23 commented on core-java-modules/core-java-streams/src/test/java/com/baeldung/stream/range/StreamRangeUnitTest.java
> +    public void whenRangeStreamUsingCollectingAndThen_thenRangePrints() {
done

2024-02-04 09:58 UTC, vinipx approved these changes

2024-02-04 09:58 UTC, merged