[BAEL-7501] Immutable and Mutable Object Examples with Tests
eugenp/tutorials pull request #15811
Opened 2024-02-03 16:20 UTC by Imranalam28

This pull request introduces comprehensive examples and test cases illustrating the concepts of mutable and immutable objects in Java. The code includes implementations of both types along with test files to validate their behavior.

### Changes:
1. Added `ImmutablePerson.java` representing an immutable object with a test file `ImmutablePersonUnitTest.java`.
2. Introduced `MutableObjectExamplesUnitTest.java`.
3. Included `ImmutableObjectExamplesUnitTest.java` to validate the immutability of `String` and `Integer` with assert statements.

These additions aim to assist developers in understanding the distinctions between mutable and immutable objects and how to handle them in Java.

2024-02-04 10:26 UTC, vinipx requested changes

2024-02-04 10:26 UTC, vinipx commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutableObjectExamplesUnitTest.java
> +    public void givenImmutableString_whenConcat_thenNotSameAndCorrectValues() {
maybe _whenConcatString_ or _whenConcatWord_ ?

2024-02-04 10:26 UTC, vinipx commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutableObjectExamplesUnitTest.java
> +    public void givenImmutableInteger_whenAdd_thenNotSameAndCorrectValue() {
maybe _whenAddInteger_ ?

2024-02-04 10:26 UTC, vinipx commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutablePersonUnitTest.java
> +        // person.setName("Jane");
let's remove it

2024-02-04 10:26 UTC, vinipx commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/MutableObjectExamplesUnitTest.java
> +    public void givenMutableString_whenModify_thenCorrectValue() {
_whenModify_ or _whenAppendElement_?

2024-02-05 09:00 UTC, Imranalam28 commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutableObjectExamplesUnitTest.java
> +    public void givenImmutableString_whenConcat_thenNotSameAndCorrectValues() {
Done

2024-02-05 09:00 UTC, Imranalam28 commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutableObjectExamplesUnitTest.java
> +    public void givenImmutableInteger_whenAdd_thenNotSameAndCorrectValue() {
Done

2024-02-05 09:00 UTC, Imranalam28 commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutablePersonUnitTest.java
> +        // person.setName("Jane");
Done

2024-02-05 09:01 UTC, Imranalam28 commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/MutableObjectExamplesUnitTest.java
> +    public void givenMutableString_whenModify_thenCorrectValue() {
Done

2024-02-05 09:31 UTC, vinipx requested changes
one minor comment left

2024-02-05 09:31 UTC, vinipx commented on core-java-modules/core-java-lang-oop-patterns/src/test/java/com/baeldung/objectmutability/ImmutablePersonUnitTest.java
> +
there is an extra line here - let's remove it

2024-02-06 07:25 UTC, vinipx approved these changes

2024-02-06 07:25 UTC, merged