BAEL-7435 | Update article "Generating Unique Positive Long using UUID in Java"
eugenp/tutorials pull request #15868
Opened 2024-02-12 15:50 UTC by hangga

https://jira.baeldung.com/browse/BAEL-7435

2024-02-14 21:40 UTC, theangrydev requested changes

2024-02-14 21:40 UTC, theangrydev commented on core-java-modules/core-java-uuid/pom.xml
> +            </plugin><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><configuration><source>8</source><target>8</target></configuration></plugin>
What happened here?

2024-02-14 21:40 UTC, theangrydev commented on core-java-modules/core-java-uuid/src/test/java/com/baeldung/uuid/UUIDPositiveLongGeneratorUnitTest.java
> +    public void whengetMostSignificantBits_thenAssertPositive() {
```suggestion
    public void whenGetMostSignificantBits_thenAssertPositive() {
```

2024-02-14 21:40 UTC, theangrydev commented on core-java-modules/core-java-uuid/src/test/java/com/baeldung/uuid/UUIDPositiveLongGeneratorUnitTest.java
> +    public void whengetLeastSignificantBits_thenAssertPositive() {
```suggestion
    public void whenGetLeastSignificantBits_thenAssertPositive() {
```

2024-02-14 21:40 UTC, theangrydev commented on core-java-modules/core-java-uuid/src/test/java/com/baeldung/uuid/UUIDPositiveLongGeneratorUnitTest.java
> +        assertThat(randomPositiveLong).isPositive();
As in https://github.com/eugenp/tutorials/pull/15692/files let's use isNotNegative, since this can technically be zero too

2024-02-14 21:40 UTC, theangrydev commented on core-java-modules/core-java-uuid/src/test/java/com/baeldung/uuid/UUIDPositiveLongGeneratorUnitTest.java
> +        assertThat(randomPositiveLong).isPositive();
As in https://github.com/eugenp/tutorials/pull/15692/files let's use isNotNegative, since this can technically be zero too

2024-02-17 18:46 UTC, theangrydev approved these changes

2024-02-26 18:59 UTC, theangrydev commented
@hangga can you check if the files from the previous version of the article like UUIDPositiveLongGenerator have been removed please? They aren't showing up as deleted in the "files changed" view for some reason

2024-02-27 01:02 UTC, hangga commented
> @hangga can you check if the files from the previous version of the article like UUIDPositiveLongGenerator have been removed please? They aren't showing up as deleted in the "files changed" view for some reason

It hasn't been deleted yet. Do we need to delete it, because it is no longer relevant in the new article?

2024-03-01 22:37 UTC, hangga commented
Hi @theangrydev it's still open..

2024-03-01 23:53 UTC, merged

2024-03-01 23:53 UTC, theangrydev commented
Thanks @hangga