JAVA-30991 :- Upgrade spring-boot-custom-starter to Boot 3.
eugenp/tutorials pull request #16140
Opened 2024-03-15 16:09 UTC by amit2103

2024-03-15 22:52 UTC, alvin577austria commented
Please also uncomment from the spring-boot-modules
/pom.xml

2024-03-15 23:07 UTC, alvin577austria requested changes

2024-03-16 07:35 UTC, amit2103 commented on spring-boot-modules/spring-boot-custom-starter/pom.xml
> +        <groupId>com.baeldung</groupId>
Fixed

2024-03-17 12:38 UTC, alvin577austria approved these changes

2024-03-17 12:42 UTC, merged