JAVA-30337 Fix failing module spring-security-web-boot-2 schema for s…
eugenp/tutorials pull request #16167
Opened 2024-03-18 21:31 UTC by timis1

…pring-security-login-redirect

2024-03-19 22:07 UTC, alvin577austria requested changes

2024-03-19 22:07 UTC, alvin577austria commented on spring-security-modules/spring-security-web-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectSecurityConfig.java
Can you please do a cleanup of the imports please, remove unused ones. Thanks!

2024-03-20 21:03 UTC, timis1 commented on spring-security-modules/spring-security-web-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectSecurityConfig.java
That imports that looks as unused are for that annotations that I commented in this class. I would suggest to leave as it is, and in case you need to run Java class configuration just to un-comment that lines without needed to import some annotations.

2024-03-20 21:26 UTC, alvin577austria commented on spring-security-modules/spring-security-web-boot-2/src/main/java/com/baeldung/loginredirect/LoginRedirectSecurityConfig.java
ok, let's leave it as is then.

2024-03-20 21:29 UTC, alvin577austria approved these changes

2024-03-20 21:31 UTC, merged