GST-9 - Initial commit, created quarkus-testcontainers submodule
eugenp/tutorials pull request #16232
Opened 2024-03-25 20:00 UTC by pauldpearson

2024-03-25 21:24 UTC, theangrydev requested changes
I'm assuming most of this is default Quarkus boilerplate. Can we trim out any unused boilerplate maybe to make it more clear which key files are actually relevant? e.g. just one Dockerfile, remove index.html, ...

2024-03-25 21:24 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/customer-service/src/test/java/info/customer/TestcontainersManager.java
> +public class TestcontainersManager implements QuarkusTestResourceLifecycleManager {
Can we rename this to make it clear that it's a custom class not a default one

2024-03-25 21:24 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/customer-service/src/test/java/info/customer/CustomerResourceTest.java
> +class CustomerResourceTest {
We have a convention to name heavy tests like this *LiveTest, which will exclude running it from the default CI build:
```suggestion
class CustomerResourceLiveTest {
```

2024-03-25 21:24 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/customer-service/src/test/java/info/customer/CustomerResourceTest.java
> +                .then().statusCode(200);
We have a standard formatter to use for Java code, can you apply it throughout please:
https://github.com/Baeldung/dev-settings/tree/main/javaCodeStyle/intellij

2024-03-26 13:26 UTC, theangrydev commented
Seeing this in CI:
```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.8.2:build (default) on project order-service: Execution default of goal io.quarkus.platform:quarkus-maven-plugin:3.8.2:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'io.quarkus.platform:quarkus-maven-plugin:3.8.2': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider was bound.
[ERROR] while locating io.quarkus.maven.BuildMojo
[ERROR] at ClassRealm[extension>io.quarkus.platform:quarkus-maven-plugin:3.8.2, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@30946e09] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value="io.quarkus.platform:quarkus-maven-plugin:3.8.2:build")
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: io.quarkus.platform:quarkus-maven-plugin:3.8.2:build
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :order-service
```

2024-03-26 15:56 UTC, pauldpearson commented
@theangrydev I'm not sure whats going on here but I am fine locally and was able to resolve the issue in the spring-project module.  Not sure if its the Java version Jenkins is using that is causing issues or not.  It looks like it is using 17.0.1 and I'd think the quarkus-maven-plugin 3.8.2 wouldn't take issue with that.

2024-03-26 17:11 UTC, theangrydev commented
@pauldpearson ok let me ping someone on our side to investigate, feel free to proceed with the article in the meantime if you're ready to

2024-03-26 18:49 UTC, theangrydev commented
https://github.com/quarkusio/quarkus/issues/32379 might be relevant

2024-03-26 21:52 UTC, theangrydev commented
@pauldpearson we use Maven 3.6.0 in CI and that seems to be the cause of the error - I'm asking the team if we can upgrade to 3.9.6

2024-03-26 22:46 UTC, pauldpearson commented
@theangrydev Okay sounds good.  If not then we can try downgrading Quarkus?

2024-03-27 07:24 UTC, asif-anwar commented
retest this please

2024-03-27 11:27 UTC, theangrydev commented
@asif-anwar one thing I'm still missing - what changes do we need to make here to respect the usual LiveTest skip mechanism?

2024-03-27 11:36 UTC, theangrydev commented
Never mind, I can see the parent is not being specified in the two child modules, that should do it

2024-03-27 11:42 UTC, theangrydev requested changes

2024-03-27 11:42 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/order-service/pom.xml
> +    <version>1.0.0-SNAPSHOT</version>
We need to add the parent module for our CI build to work properly:
```suggestion
    <modelVersion>4.0.0</modelVersion>
    <groupId>info.order</groupId>
    <artifactId>order-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>

  <parent>
    <groupId>com.baeldung</groupId>
    <artifactId>quarkus-testcontainers</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
```

2024-03-27 11:42 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/pom.xml
> +    <version>1.0-SNAPSHOT</version>
```suggestion
    <version>1.0.0-SNAPSHOT</version>
```

2024-03-27 11:42 UTC, theangrydev commented on quarkus-modules/quarkus-vs-springboot/spring-project/pom.xml
> +            </plugin>
```suggestion
```

2024-03-27 11:42 UTC, theangrydev commented on quarkus-modules/quarkus-testcontainers/customer-service/pom.xml
> +    <version>1.0.0-SNAPSHOT</version>
We need to add the parent module for our CI build to work properly:
```suggestion
    <modelVersion>4.0.0</modelVersion>
    <groupId>info.customer</groupId>
    <artifactId>customer-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <parent>
        <groupId>com.baeldung</groupId>
        <artifactId>quarkus-testcontainers</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
```

2024-03-27 12:22 UTC, pauldpearson commented
🤞 Pushed up suggested changes

2024-03-27 13:10 UTC, theangrydev commented
@pauldpearson quarkus-modules/quarkus-vs-springboot/spring-project/pom.xml is a module for another article, so I wouldn't expect any changes at all there vs master

2024-03-27 13:21 UTC, theangrydev commented
@asif-anwar we are now seeing:
```
[INFO] quarkus-project 0.1-SNAPSHOT ....................... SUCCESS [ 15.408 s]
[INFO] spring-project 0.1-SNAPSHOT ........................ FAILURE [  3.196 s]
[INFO] quarkus-funqy 1.0.0-SNAPSHOT ....................... SKIPPED
[INFO] quarkus-testcontainers 1.0.0-SNAPSHOT .............. SKIPPED
[INFO] order-service 1.0.0-SNAPSHOT ....................... SKIPPED
[INFO] customer-service 1.0.0-SNAPSHOT .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:43 min
[INFO] Finished at: 2024-03-27T12:25:27Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project spring-project: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test failed: java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory: org.junit.platform.launcher.core.LauncherFactory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-project
```

Failure at module unrelated to this PR spring-project

This also reproduces on origin/master (without these PR changes) with mvn 3.6.3 and java 17.0.10

2024-03-27 13:35 UTC, theangrydev commented
@pauldpearson I'm not clear how quarkus-modules/quarkus-vs-springboot/spring-project/pom.xml was working before but looks like your change does fix it
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
```

So let's go back to that sorry - and extract a `${maven-surefire-plugin.version}` property for the version there

2024-03-27 15:42 UTC, theangrydev approved these changes

2024-03-27 15:56 UTC, pauldpearson commented
Victory!

2024-06-21 13:21 UTC, theangrydev commented
retest this

2024-06-21 13:23 UTC, theangrydev approved these changes

2024-06-21 13:23 UTC, theangrydev commented
retest this please

2024-06-23 15:36 UTC, pauldpearson commented
@theangrydev I'm getting the same failure locally as what is showing in Jenkins

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project spring-project: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests: ClassSelector [className = 'com.baeldung.spring_project.SpringContextTest'] resolution failed: 'java.util.stream.Stream org.junit.platform.commons.support.ReflectionSupport.streamNestedClasses(java.lang.Class, java.util.function.Predicate)' -> [Help 1]`

2024-07-06 15:11 UTC, theangrydev commented
retest this please

2024-07-09 11:11 UTC, theangrydev commented
retest this please

2024-07-11 22:04 UTC, theangrydev approved these changes

2024-07-20 17:56 UTC, merged