[BAEL-7669] Example code for article. Setting global TimeZone in spring
eugenp/tutorials pull request #16260
Opened 2024-03-29 08:44 UTC by bpstelios10

* Added logback-test.xml for spring tests, to set level to INFO

2024-04-02 08:01 UTC, ashleyfrieze requested changes

2024-04-02 08:01 UTC, ashleyfrieze commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/GlobalTimezoneBeanFactoryPostProcessor.java
> +    private static final Logger logger = LoggerFactory.getLogger(GlobalTimezoneBeanFactoryPostProcessor.class);
`LOGGER`

2024-04-02 08:01 UTC, ashleyfrieze commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/MainApplication.java
> +        // TimeZone.setDefault(TimeZone.getTimeZone("GMT+08:00"));
Explain why this is commented out.

2024-04-02 08:01 UTC, ashleyfrieze commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/MainApplication.java
> +    private static final Logger logger = LoggerFactory.getLogger(MainApplication.class);
`LOGGER`

2024-04-02 08:01 UTC, ashleyfrieze commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/MainApplication.java
> +        // TimeZone.setDefault(TimeZone.getTimeZone("GMT+08:00"));
Similarly explain why this is commented out - e.g. `For doing it <this other way> then use this instead`

2024-04-04 12:45 UTC, bpstelios10 commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/GlobalTimeZoneBean.java
> +    private static final Logger logger = LoggerFactory.getLogger(GlobalTimeZoneBean.class);
i leave it as `private static final Logger log` since `log.info()` looks more familiar (cause of lombok), but happy to go with this convention

2024-04-04 18:30 UTC, ashleyfrieze commented on spring-core-4/src/main/java/com/baeldung/globaltimezone/GlobalTimeZoneBean.java
> +    private static final Logger logger = LoggerFactory.getLogger(GlobalTimeZoneBean.class);
Lombok is evil. Let's follow the Java standard that `private static final` is uppercase.

2024-04-07 17:39 UTC, bpstelios10 commented
I had some weird conflicts. There were no conflicts really. But anyway, i rebased over master, then some issue again with the spaces in pom.xml so i had to force push a last commit. Should be all right now

2024-04-14 16:42 UTC, KevinGilmore commented on spring-core-4/pom.xml
> +        </dependency>
The spring-core modules are meant to exclude Spring Boot entirely. We need to move your code to one of the Spring Boot modules.

2024-04-18 17:21 UTC, merged