[int-to-boolean] int->boolean
eugenp/tutorials pull request #16467
Opened 2024-04-21 21:55 UTC by sk1418

2024-04-21 23:35 UTC, theangrydev requested changes

2024-04-21 23:35 UTC, theangrydev commented on core-java-modules/core-java-numbers-4/src/test/java/com/baeldung/booleantoint/IntToBooleanUnitTest.java
> +        assertThrows(IllegalArgumentException.class, () ->BooleanUtils.toBoolean(-42, trueValue, falseValue));
Fix formatting

2024-04-22 23:28 UTC, theangrydev approved these changes

2024-06-11 13:39 UTC, lor6 commented
retest this please

2024-06-11 14:48 UTC, merged