Bael 7772 my batis vs hibernate
eugenp/tutorials pull request #16637
Opened 2024-05-12 09:44 UTC by zeesh49

2024-05-14 14:22 UTC, theangrydev requested changes

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/pom.xml
> +        </dependency>
Fix formatting + include a property like ${hibernate.version}

Same for the mybatis dependency

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/pom.xml
> +            <version>5.10.2</version>
Use existing ${junit-jupiter.version} from the parent

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/pom.xml
> +            <version>2.2.224</version>
Use existing ${h2.version} from the parent

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/pom.xml
> +        <maven.compiler.target>17</maven.compiler.target>
These are not required, due to the way the parent modules are set up, specifying java.version is sufficient
```suggestion
```

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/main/java/com/baeldung/mybatisvshibernate/Student.java
> +    }
If this is required for Hibernate, make it clear with a comment
```suggestion
    public Student() {
        // required for Hibernate
    }
```

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/HibernateUnitTest.java
> +        ;
```suggestion

```

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/HibernateUnitTest.java
> +        Assertions.assertEquals(zeesh, zeeshFetched);
Add static import for assertEquals
```suggestion
        assertEquals(zeesh, zeeshFetched);
```
(similar elsewhere)

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/MybatisUnitTest.java
> +        try(SqlSession sf = ssf.openSession()) {
This whitespace issue is a sign that you might not be using the Baeldung formatter? Can you apply it to all files so we have our standard formatting rules applied
```suggestion
        try (SqlSession sf = ssf.openSession()) {
```

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/resources/StudentMapper.xml
> +        </selectKey>-->
Why is this commented out?

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/MybatisUnitTest.java
> +        Student bilalFetched;
Move these declarations closer to their usage

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/HibernateUnitTest.java
> +        }
We want the test to fail if there is an exception here, so throw it:
```suggestion
        } catch (Exception e) {
            StandardServiceRegistryBuilder.destroy(registry);
            throw e;
        }
```

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/HibernateUnitTest.java
> +    public void hibernateExample() {
We use BDD style given_when_then or when_then naming for our test methods

2024-05-14 14:22 UTC, theangrydev commented on persistence-modules/mybatis-vs-hibernate/src/test/java/com/baeldung/mybatisvshibernate/MybatisUnitTest.java
> +    public void whenStudentsInsertedThenSearched() throws IOException {
We use BDD style given_when_then or when_then naming for our test methods

2024-06-11 13:42 UTC, lor6 commented
retest this please

2024-07-10 13:04 UTC, closed without merging