[BAEL-7993] Count the number of occurrences in an array in Java
eugenp/tutorials pull request #16714
Opened 2024-05-24 13:26 UTC by lucaCambi77

count occurrences in array and tests

2024-05-29 20:51 UTC, ashleyfrieze requested changes

2024-05-29 20:51 UTC, ashleyfrieze commented on algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/permutation/StringPermutationUnitTest.java
> +
Do we need this?

2024-06-11 13:46 UTC, lor6 commented
retest this please

2024-06-18 11:41 UTC, ashleyfrieze commented on algorithms-modules/algorithms-miscellaneous-9/src/test/java/com/baeldung/algorithms/permutation/StringPermutationUnitTest.java
> +
> this is a minor thing we can do at any time

Including never. It just adds noise to this PR. However, leave it be.

I appreciate the "boy scout rule" here, cleaning up the code. Perhaps this isn't the project to do that in. But it's not worth taking time to revert it.

2024-07-08 11:44 UTC, merged