PR:BAEL-6037
eugenp/tutorials pull request #17170
Opened 2024-07-28 12:24 UTC by BahaaHelmy

PR to the article named Java Enums with all HTTP status codes [BAEL-6037].

2024-07-28 22:22 UTC, theangrydev requested changes

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <junit.version>4.13.2</junit.version>
We use JUnit5 for new articles

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <maven.compiler.target>20</maven.compiler.target>
What is the minimum Java version required? We shouldn't set this higher than the minimum actually required for this article

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        </dependency>
These are already defined in the parent module
```suggestion
```

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        </dependency>
These are already defined in the parent module
```suggestion
```

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <!-- OkHttp Dependency -->
Delete these comments, the dependency is clear from the groupId/artifactId already
```suggestion
```

2024-07-28 22:22 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <spring.web.version>5.3.10</spring.web.version>
Check versions of the libraries and use the latest stable versions

2024-07-28 22:22 UTC, theangrydev commented on pom.xml
> +	        <module>libraries-http-3</module>
Look for all the places that libraries-http-2 is mentioned and reorder like:
                <module>libraries-http</module>
                <module>libraries-http-2</module>
                <module>libraries-http-3</module>

2024-07-28 22:23 UTC, theangrydev requested changes

2024-07-28 22:23 UTC, theangrydev commented on libraries-http-3/src/test/java/com/baeldung/enumwithallhttpstatuscodes/EnumWithHttpStatusCodesLiveTest.java
> +import static org.junit.Assert.assertEquals;
Use JUnit5 not JUnit4

2024-07-28 22:23 UTC, theangrydev commented on libraries-http-3/src/test/java/com/baeldung/enumwithallhttpstatuscodes/EnumWithHttpStatusCodesUnitTest.java
> +import static org.junit.Assert.assertEquals;
Use JUnit5 not JUnit4

2024-07-29 17:21 UTC, theangrydev requested changes

2024-07-29 17:21 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <okhttp.version>4.10.0</okhttp.version>
The latest stable version is 4.12.0 https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp

2024-07-29 17:21 UTC, theangrydev commented on libraries-http-3/pom.xml
> +        <spring.web.version>6.1.5</spring.web.version>
The latest stable version is 6.1.11 https://mvnrepository.com/artifact/org.springframework/spring-web

2024-07-29 22:19 UTC, theangrydev approved these changes

2024-08-02 07:44 UTC, theangrydev commented
retest this please

2024-08-07 13:47 UTC, lor6 commented
retest this please

2024-08-07 21:21 UTC, merged