BAEL-4514 - Excluding Transitive Dependencies in Gradle
eugenp/tutorials pull request #17224
Opened 2024-08-03 11:50 UTC by hangga

2024-08-10 13:09 UTC, theangrydev requested changes

2024-08-10 13:09 UTC, theangrydev commented on gradle-modules/gradle-core/build.gradle
> +
remove extra empty line

2024-08-10 13:09 UTC, theangrydev commented on gradle-modules/gradle-core/excluding-transitive-dependencies/build.gradle
> +//    implementation 'com.google.guava:guava:33.2.0-jre' // enforce with kordamp
```suggestion
    //    implementation 'com.google.guava:guava:33.2.0-jre' // enforce this cannot be included with kordamp
```

2024-08-11 04:07 UTC, hangga commented
Hi @theangrydev Hi Liam. Maybe I'll make a new PR.
I just accidentally deleted git ignore so there are 70 files that shouldn't have been pushed.

2024-08-11 04:57 UTC, closed without merging