Java 37799 :- Upgrade to boot 3.2.2 for Spring Boot Libraries.
eugenp/tutorials pull request #17452
Opened 2024-08-25 13:35 UTC by amit2103

2024-08-31 21:42 UTC, alvin577austria approved these changes

2024-08-31 21:54 UTC, alvin577austria requested changes

2024-08-31 21:54 UTC, alvin577austria commented on spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/annotation/scanner/AnnotationScannerApp.java
> +import org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration;
Does not seem to be used. Maybe we can remove this.

2024-08-31 21:54 UTC, alvin577austria commented on spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/jobrunr/config/StorageProviderConfig.java
> +import org.springframework.beans.factory.annotation.Qualifier;
Unused.

2024-08-31 21:54 UTC, alvin577austria commented on spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/jobrunr/config/StorageProviderConfig.java
> +import org.springframework.web.client.RestTemplate;
Unused.

2024-08-31 21:54 UTC, alvin577austria commented on spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/kong/StockApp.java
> +import org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration;
Seems unused.

2024-08-31 21:54 UTC, alvin577austria commented on spring-boot-modules/spring-boot-libraries-2/src/main/java/com/baeldung/modulith/Application.java
> +import org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration;
Unused.

2024-09-01 09:41 UTC, amit2103 commented on spring-boot-modules/pom.xml
> +
Intentional because of the libraries

2024-09-01 11:35 UTC, alvin577austria approved these changes

2024-09-01 11:35 UTC, merged