Query JPA repository with single table inheritance subtypes
eugenp/tutorials pull request #17650
Opened 2024-09-21 13:06 UTC by mee-omi

2024-09-24 10:16 UTC, theangrydev requested changes

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/main/java/com/baeldung/jpa/subtypes/entity/Employee.java
> +        // TODO Auto-generated constructor stub
```suggestion
```

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/main/java/com/baeldung/jpa/subtypes/config/PersistenceConfig.java
> +        final LocalContainerEntityManagerFactoryBean em = new LocalContainerEntityManagerFactoryBean();
Remove unnecessary final usage (same elsewhere)
```suggestion
        LocalContainerEntityManagerFactoryBean em = new LocalContainerEntityManagerFactoryBean();
```

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/test/java/com/baeldung/jpa/subtypes/JPAInheritanceSingleTableTest.java
> +class JPAInheritanceSingleTableTest {
We follow https://google.github.io/styleguide/javaguide.html for naming conventions
```suggestion
class JpaInheritanceSingleTableTest {
```

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/main/java/com/baeldung/jpa/subtypes/SubTypeJPAApplication.java
> +public class SubTypeJPAApplication {
We follow https://google.github.io/styleguide/javaguide.html for naming conventions
```suggestion
public class SubTypeJpaApplication {
```

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/test/java/com/baeldung/jpa/subtypes/JPAInheritanceSingleTableTest.java
> +    void givenRecordsInserted_whenDiscrimnatorQueryUsed_thenEmployeesRecordsByTypeRetruned() {
Fix typo (same in other tests)
```suggestion
    void givenRecordsInserted_whenDiscrimnatorQueryUsed_thenEmployeesRecordsByTypeReturned() {
```

2024-09-24 10:16 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/test/java/com/baeldung/jpa/subtypes/JPAInheritanceSingleTableTest.java
> +    public void tearDown() {
```suggestion
    void tearDown() {
```

2024-09-25 19:18 UTC, theangrydev requested changes

2024-09-25 19:18 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/main/java/com/baeldung/jpa/subtypes/config/PersistenceConfig.java
> +    final Properties additionalProperties() {
Remove unnecessary final + make private if possible 
```suggestion
    private Properties additionalProperties() {
```

2024-09-25 19:18 UTC, theangrydev commented on persistence-modules/spring-jpa-3/src/test/java/com/baeldung/jpa/subtypes/SubTypeJpaImplTest.java
> +class SubTypeJpaImplTest {
I prefer the old name, it's clearer
```suggestion
class JpaInheritanceSingleTableTest {
```

2024-09-26 12:48 UTC, theangrydev approved these changes

2024-09-29 15:28 UTC, KevinGilmore commented on persistence-modules/spring-jpa-3/pom.xml
> +	<packaging>war</packaging>
We need to revert the spacing to use spaces, not tabs. There should not be this many changes to the pom.xml.

2024-09-29 15:31 UTC, KevinGilmore commented on persistence-modules/spring-jpa-3/src/main/java/com/baeldung/jpa/subtypes/repository/EmployeeRepository.java
> +    List<PermanentEmployee> findAllPermEmplouees();
```suggestion
    List<PermanentEmployee> findAllPermEmployees();
```

2024-10-09 21:10 UTC, merged