codebase/spring-ai-with-chromadb-vector-store [BAEL-8848]
eugenp/tutorials pull request #17970
Opened 2024-11-14 04:17 UTC by hardikSinghBehl

Codebase for the article: **Spring AI With ChromaDB Vector Store**

2024-11-17 16:15 UTC, hardikSinghBehl commented on spring-ai-2/src/test/java/com/baeldung/springai/chromadb/TestcontainersConfiguration.java
> +    }
review incorporated.

2024-11-17 16:16 UTC, hardikSinghBehl commented on spring-ai-2/src/main/java/com/baeldung/springai/chromadb/VectorStoreInitializer.java
> +        PoetryFetcher
review incorporated. Have used the map() approach since the add() method of VectorStore only takes a list of Documents.

2024-11-19 12:27 UTC, theangrydev approved these changes

2024-11-19 22:36 UTC, theangrydev requested changes

2024-11-19 22:36 UTC, theangrydev commented on spring-ai-2/pom.xml
> +           </releases>
This should be:
```suggestion
 <snapshots>
      <enabled>false</enabled>
    </snapshots>
```

2024-11-19 23:11 UTC, hardikSinghBehl commented on spring-ai-2/pom.xml
> +           </releases>
fixed.

2024-11-20 11:48 UTC, theangrydev commented
retest this please

2024-11-27 07:11 UTC, merged