BAEL-4443 Reading HTTP ResponseBody as a String
eugenp/tutorials pull request #9916
Opened 2020-08-24 16:31 UTC by oussama-benmahmoud

2020-09-04 15:52 UTC, KevinGilmore requested changes
Use a more specific package name, and remove the .gitignore

2020-09-19 20:07 UTC, oussama-benmahmoud commented on httpclient-2/src/test/java/com/baeldung/httpclient/ApacheHttpClientUnitTest.java
> +package com.baeldung.httpclient;
Ok, I'll do this.

2020-09-19 20:08 UTC, oussama-benmahmoud commented on httpclient-2/.gitignore
> +*.class
I followed the httpclient module but ok I'll delete it.

2020-09-26 15:47 UTC, KevinGilmore approved these changes

2020-09-28 03:02 UTC, davidmartinezbarua commented
retest this please

2020-09-28 18:03 UTC, lor6 commented
retest this please

2020-09-28 18:15 UTC, oussama-benmahmoud commented
@lor6 the issue is related to a failed test in another module, where there's no link/dep with httpclient-2 module, I tried to run the test on my pc and it worked fine, can you try to rerun the pipeline please?

2020-09-28 18:37 UTC, davidmartinezbarua commented
retest this please

2020-09-29 13:29 UTC, merged